name: Run Tests on Mac ARM

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install Poetry
      run: |
        pip install poetry
        poetry config virtualenvs.create false

    - name: Install Dependencies
      run: poetry install

    - name: Run unittest tests
      run: poetry run python -m unittest discover -s tests -p 'test_a*.py'

    - name: Build with Poetry
      run: |
        poetry build